version: 2

references:

  install_ubuntu_python2: &install_ubuntu_python2
    run:
      name: Install Python 2 on Ubuntu.
      command: |
        apt-get update -qy
        apt-get install -y python-dev python-pip
        pip install --upgrade matplotlib==2.0.2 numpy six setuptools scipy pytest

  install_ubuntu_python3: &install_ubuntu_python3
    run:
      name: Install Python 3 on Ubuntu and set it to be the default.
      command: |
        apt-get update -qy
        apt-get install -y python3-dev python3-pip
        pip3 install --upgrade matplotlib==2.0.2 numpy six setuptools scipy pytest
        ln -s /usr/bin/python3 /usr/bin/python  # this is dirty

  test_ubuntu_example_python2: &test_ubuntu_example_python2
    run:
      name: Run the random search example on Ubuntu with Python 2.
      command: |
        # install dependencies
        apt-get install -y build-essential
        # install coco
        python do.py run-python
        python do.py install-postprocessing
        # run the example
        cd code-experiments/build/python
        python example_experiment.py bbob
        # postprocess the results
        python -m cocopp -o ./postproc ./exdata

  test_ubuntu_example_python3: &test_ubuntu_example_python3
    run:
      name: Run the random search example on Ubuntu with Python 3.
      command: |
        # install dependencies
        apt-get install -y build-essential
        # install coco
        python3 do.py run-python
        python3 do.py install-postprocessing
        # run the example
        cd code-experiments/build/python
        python3 example_experiment.py bbob
        # postprocess the results
        python3 -m cocopp -o ./postproc ./exdata

  test_ubuntu_python2: &test_ubuntu_python2
    run:
      name: Run Python 2 coco tests on Ubuntu.
      command: |
        apt-get install -y git
        pip install --upgrade cython
        python do.py test-python

  test_ubuntu_python3: &test_ubuntu_python3
    run:
      name: Run Python 3 coco tests on Ubuntu.
      command: |
        apt-get install -y git
        pip3 install --upgrade cython
        python3 do.py test-python

  test_ubuntu_other_python2: &test_ubuntu_other_python2
    run:
      name: Run all coco tests except for Python on Ubuntu with Python 2.
      command: |
        # install extra dependencies for tests
        apt-get install -y liboctave-dev openjdk-8-jdk \
                                libcmocka-dev mlocate texlive-full
        updatedb
        # test coco
        python do.py test-c
        python do.py test-octave
        python do.py test-java
        python do.py test-preprocessing
        python do.py test-postprocessing-all
      no_output_timeout: 7200

  test_ubuntu_other_python3: &test_ubuntu_other_python3
    run:
      name: Run all coco tests except for Python on Ubuntu with Python 3.
      command: |
        # install extra dependencies for tests
        apt-get install -y liboctave-dev openjdk-8-jdk \
                                libcmocka-dev mlocate texlive-full
        updatedb
        # test coco
        python3 do.py test-c
        python3 do.py test-octave
        python3 do.py test-java
        python3 do.py test-preprocessing
        python3 do.py test-postprocessing-all
      no_output_timeout: 7200

jobs:

  test_ubuntu_rolling_python3:
    docker:
      - image: ubuntu:rolling
        environment:
          CC: gcc
    working_directory: ~/coco
    steps:
      - checkout
      - *install_ubuntu_python3
      - *test_ubuntu_example_python3
      - *test_ubuntu_python3
      - *test_ubuntu_other_python3

  test_ubuntu_latest_python2:
    docker:
      - image: ubuntu:latest
        environment:
          CC: gcc
    working_directory: ~/coco
    steps:
      - checkout
      - *install_ubuntu_python2
      - *test_ubuntu_example_python2
      - *test_ubuntu_python2
      - *test_ubuntu_other_python2

workflows:

  version: 2
  test-matrix:
    jobs:
      - test_ubuntu_rolling_python3
      - test_ubuntu_latest_python2
