version: 2

references:

  install_ubuntu_python2: &install_ubuntu_python2
    run:
      name: Install Python 2 on Ubuntu.
      command: |
        sudo apt-get update -qy
        sudo apt-get install -y python-dev
        sudo pip install --upgrade numpy matplotlib six setuptools scipy pytest

  install_ubuntu_python3: &install_ubuntu_python3
    run:
      name: Install Python 3 on Ubuntu and set it to be the default.
      command: |
        sudo apt-get update -qy
        sudo apt-get install -y python3-dev
        sudo pip3 install --upgrade numpy matplotlib six setuptools scipy pytest

  test_ubuntu_example: &test_ubuntu_example
    run:
      name: Run the random search example on Ubuntu.
      command: |
        # install dependencies
        sudo apt-get install -y build-essential
        # install coco
        sudo python do.py run-python
        sudo python do.py install-postprocessing
        # run the example
        cd code-experiments/build/python
        sudo python example_experiment.py bbob
        # postprocess the results
        sudo python -m cocopp -o ./postproc ./exdata

  test_ubuntu_python2: &test_ubuntu_python2
    run:
      name: Run Python 2 coco tests on Ubuntu.
      command: |
        sudo apt-get install -y git cython
        sudo python do.py test-python

  test_ubuntu_python3: &test_ubuntu_python3
    run:
      name: Run Python 3 coco tests on Ubuntu.
      command: |
        sudo apt-get install -y git cython3
        sudo python do.py test-python

  test_ubuntu_other: &test_ubuntu_other
    run:
      name: Run all coco tests except for Python on Ubuntu.
      command: |
        # install extra dependencies for tests
        sudo apt-get install -y liboctave-dev openjdk-8-jdk \
                                libcmocka-dev mlocate texlive-full
        updatedb
        # test coco
        python do.py test-c
        python do.py test-octave
        python do.py test-java
        python do.py test-preprocessing
        python do.py test-postprocessing-all
      no_output_timeout: 7200

jobs:

  test_ubuntu_rolling_python3:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/coco
    steps:
      - checkout
      - *install_ubuntu_python3
      - *test_ubuntu_example
      - *test_ubuntu_python3
      - *test_ubuntu_other

  test_ubuntu_latest_python2:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/coco
    steps:
      - checkout
      - *install_ubuntu_python2
      - *test_ubuntu_example
      - *test_ubuntu_python2
      - *test_ubuntu_other

workflows:

  version: 2
  test-matrix:
    jobs:
      - test_ubuntu_rolling_python3
      - test_ubuntu_latest_python2
